--- 
abstract: Keep imports out of your namespace
author: 
  - Florian Ragwitz <rafl@debian.org>
generated_by: Dist::Zilla::Plugin::MetaYaml version 1.006
license: perl
name: namespace-autoclean
requires: 
  B::Hooks::EndOfScope: 0.07
  Class::MOP: 0.80
  namespace::clean: 0.11
version: 0.04
