use strict;
use warnings;
use Test::More;

# generated by Dist::Zilla::Plugin::Test::PodSpelling 2.006001
use Test::Spelling 0.12;
use Pod::Wordlist;


add_stopwords(<DATA>);
all_pod_files_spelling_ok( qw( bin lib  ) );
__DATA__
Florian
Ragwitz
rafl
Andrew
Rodland
andrew
Chris
Prather
cprather
Dave
Rolsky
autarch
Felix
Ostmann
sadrak
Karen
Etheridge
ether
Kent
Fredric
kentfredric
Shawn
Moore
sartak
Tomas
Doran
bobtfish
lib
namespace
autoclean
